version: '3.8'

services:
  spark-consumer:
    build:
      context: ./implementation
      dockerfile: Dockerfile
    container_name: spark-consumer-implementation
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - DB_HOST=transactions-db
      - DB_PORT=5432
      - DB_USER=finance_db_user
      - DB_PASSWORD=1234
      - DB_NAME=finance_db
      - SPARK_LOCAL_IP=127.0.0.1
      - SPARK_DRIVER_HOST=spark-consumer
    volumes:
      - spark-checkpoints:/app/checkpoints
      - spark-temp:/tmp/spark_temp
    ports:
      - "4040:4040"
      - "4041:4041"
    networks: [finance-shared-net]
    restart: unless-stopped

volumes:
  spark-checkpoints:
  spark-temp:

networks:
  finance-shared-net:
    external: true
    name: finance-shared-net
